# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: accounts-deployment
deploymentLabel: accounts

replicaCount: 1

docker:
  repository: pkarugu/banking-accounts:latest

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false
rabbitmq_enabled: true
secondary_port_enabled: false

containerPort: 8085

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085
