# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eurekaserver-deployment
deploymentLabel: eurekaserver

replicaCount: 1

docker:
  repository: pkarugu/eureka-server:latest

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false
keycloak_enabled: false
rabbitmq_enabled: true
secondary_port_enabled: false

containerPort: 8055

service:
  type: ClusterIP
  port: 8055
  targetPort: 8055
