# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 1

docker:
  repository: pkarugu/banking-cards:latest

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false
rabbitmq_enabled: true
secondary_port_enabled: false

containerPort: 8070

service:
  type: ClusterIP
  port: 8070
  targetPort: 8070
