# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 1

docker:
  repository: pkarugu/banking-loans:latest

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false
rabbitmq_enabled: true
secondary_port_enabled: false

containerPort: 8090

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8090
