{{- define "common.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
          image: {{ .Values.docker.repository }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
            {{- if .Values.secondary_port_enabled }}
            - containerPort: {{ .Values.secondaryContainerPort }}
              protocol: TCP
            {{- end }}
          env:
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILES_ACTIVE
          {{- end }}
          {{- if .Values.zipkin_enabled }}
          - name: SPRING_ZIPKIN_BASEURL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_ZIPKIN_BASEURL
          {{- end }}
          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_CONFIG_IMPORT
          {{- end }}
          {{- if .Values.eureka_enabled }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          {{- end }}
          {{- if .Values.rabbitmq_enabled }}
          - name: SPRING_ZIPKIN_SENDER_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_ZIPKIN_SENDER_TYPE
          - name: SPRING_ZIPKIN_RABBITMQ_QUEUE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: RABBIT_QUEUE
          - name: SPRING_RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_HOST
          - name: SPRING_RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_RABBITMQ_PORT
          - name: SPRING_RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: RABBIT_USER
          - name: SPRING_RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: RABBIT_PASSWORD
          {{- end }}
{{ end -}}